## For information on how to use thie file, see the documentation at the repo home:
## github.com/sahassar/boltredirector

# Redirects - The Main Redirects for this Installation
redirects:
    # Redirects om de topnav goed te laten werken. Linkt door naar eerste child via deze redirect. EP-125
    # parent : first child
    '/page/share-your-data': '/share-your-data/process'
    '/share-your-data': '/share-your-data/process'
    '/page/about-us': '/about-us/mission'
    '/about-us': '/about-us/mission'
    '/page/network-association': ' /network-association/sign-up'
    '/network-association': '/network-association/sign-up'

    # New redirects for "Redesign 2019 / 2020", as provided by Dasha on 2020-03-11
    '/home': '/'
    '/what-we-do': '/about-us/mission'
    '/resources': '/about-us/services-and-tools'
    '/services/discovery': '/page/collections'
    '/services/discovery/collections': '/page/collections'
    '/services/discovery/thematic-collections': '/page/collections'
    #'/page/creating-editorial': '/page/creating-editorial'
    #'/what-we-do/academic-research': '/page/academic-research'
    '/what-we-do/creative-industries': '/about-us/services-and-tools'
    '/what-we-do/cultural-heritage-institutions': '/'
    '/what-we-do/education': '/page/education'
    '/resources/datasets': '/page/datasets'
    '/services/facilitating-innovation': '/about-us/services-and-tools'
    '/resources/apps': '/page/apps'
    '/services/facilitating-innovation/co-creation': '/data/wotify-card-sets'
    '/page/managing-europeana-projects': '/about-us/projects'
    '/what-we-do/campaigns': '/page/campaigns'
    '/page/hispana': 'https://hispana.mcu.es/es/inicio/inicio.do'
    '/page/sustainability-planning': '/about-us/projects'
    '/page/high-resolution-images': 'https://www.europeana.eu/'
    '/page/high-resolution-images-1': 'https://www.europeana.eu/portal/en/exhibitions/pioneers'
    '/resources/document-archive/project-list': '/about-us/projects'
    '/resources/standardization-tools/rightsstatements-org': '/page/rightsstatements-org'
    '/resources/document-archive/r-d-recommendations': '/page/r-d-recommendations'
    '/page/r-d-tools': '/page/europeanatech-insight'
    '/services': '/about-us/services-and-tools'
    '/services/facilitating-innovation/crowd-and-matchfunding': '/about-us/services-and-tools'
    '/services/facilitating-innovation/grants-programme': '/page/grants-programme'
    '/what-we-do/projects': '/about-us/projects'
    '/resources/document-archive': '/network-association/documentation'
    '/page/linked-open-data-credits': '/page/linked-open-data'
    '/services/discovery/online-exhibitions': '/page/creating-editorial'
    '/what-we-do/member-states': '/page/member-states'
    '/page/creative-industries-datasets': '/page/datasets'
    '/page/jamdots': '/post/europeana-for-education-policy-recommendations'
    '/page/europe-at-work-1': 'https://www.europeana.eu/portal/en/explore/galleries/working-lives-across-europe'
    '/our-mission': '/about-us/mission'
    '/our-mission/about-us': '/about-us/mission'
    '/jobs': '/about-us/jobs'
    '/blog': '/page/news'
    '/resources/document-archive/press-releases': '/page/press'
    '/press': '/page/press'
    '/resources/document-archive/europeana-in-the-news': '/page/europeana-in-the-news'
    '/resources/document-archive/publications': '/page/publications'
    '/our-mission/foundation-governing-board': '/about-us/governance'
    '/resources/document-archive/governing-board-papers-documents': '/about-us/governance'
    '/our-mission/who-we-are': '/about-us/mission'
    '/our-mission/history': '/about-us/mission'
    '/our-mission/office-employees': '/page/office-employees'
    '/contact-us': '/about-us/office-employees'
    '/resources/europeana-playbook': '/about-us/mission'
    '/page/what-we-believe-in': '/about-us/mission'
    '/page/guiding-values': '/about-us/mission'
    '/page/sharing-our-offices-and-our-ideas': '/about-us/mission'
    '/page/roles-and-responsibilities': '/about-us/mission'
    '/page/decision-making': '/about-us/mission'
    '/page/meeting-guidance': '/about-us/mission'
    '/page/communication-collaboration-and-planning': '/about-us/mission'
    '/page/hitchcock-sessions': '/about-us/mission'
    '/page/agile-methodology': '/about-us/mission'
    '/page/directors': '/about-us/mission'
    '/page/people-and-business-support': '/about-us/mission'
    '/page/collections-team': '/about-us/mission'
    '/page/re-use-team': '/about-us/mission'
    '/page/data-partner-services': '/about-us/mission'
    '/page/programme-and-network': '/about-us/mission'
    '/page/marketing-and-communications': '/about-us/mission'
    '/page/research-and-development': '/about-us/mission'
    '/page/product-owner-and-design-team': '/about-us/mission'
    '/page/software-development-and-infrastructure': '/about-us/mission'
    '/page/about-the-playbook': '/about-us/mission'
    '/page/teams': '/about-us/mission'
    '/page/annual-report-2018': '/page/annual-report-2018-a-decade-of-democratising-culture'
    '/resources/apis/entity': '/page/entity'
    '/resources/apis/intro': '/page/intro'
    '/resources/apis/sparql': '/page/sparql'
    '/resources/apis/record': '/page/record'
    '/resources/apis/search': '/page/search'
    '/resources/apis': '/page/apis'
    '/get-api': '/pages/get-api'
    '/resources/apis/annotations': '/page/annotations'
    '/resources/apis/oai-pmh-service': '/page/oai-pmh-service'
    '/resources/apis/iiif': '/page/iiif'
    # '/services/facilitating-innovation/take-the-challenge': '/about-us/activities'
    '/services/data-publication-services': '/share-your-data/process'
    '/page/reasons-to-share-your-data-on-europeana-collections': '/share-your-data/process'
    '/page/what-kind-of-content-is-europeana-looking-for': '/share-your-data/process'
    '/services/data-publication-services/new-provider': '/share-your-data/process'
    '/services/data-publication-services/aggregators': '/page/aggregators'
    '/network-association': '/network-association/sign-up'
    '/network-association/about-our-network': '/network-association/sign-up'
    '/resources/document-archive/newsletters-and-updates': '/network-association/documentation'
    '/resources/document-archive/task-force-recommendations': '/network-association/task-forces'
    '/page/past-task-forces': '/network-association/task-forces'
    '/page/task-force-terms-of-reference': '/page/terms-of-reference-for-task-forces'
    '/network-association/special-interest-groups': '/network-association/communities'
    '/network-association/special-interest-groups/europeanatech': '/page/europeanatech'
    '/page/contribute-to-europeanatech': '/page/europeanatech'
    '/network-association/special-interest-groups/europeana-education': '/page/europeana-education'
    '/page/europeana-in-your-classroom-building-21st-century-competences-with-digital-cultural-heritage-mooc': '/post/europeana-mooc-now-available-in-five-languages'
    '/page/about-research': '/page/grants-programme'
    '/network-association/special-interest-groups/research-community': '/page/europeana-research'
    #'/page/europeana-research-events-grants-programme-2019-call-for-submissions': '/page/grants-programme'
    '/page/research-grants-programme-submissions-2019': '/page/grants-programme'
    '/what-we-do/impact': '/page/impact'
    '/page/impact-resources': '/page/impact'
    '/network-association/special-interest-groups/europeana-communicators-group': '/page/europeana-communicators-group'
    '/network-association/working-groups': '/network-association/task-forces'
    '/page/working-group-terms-of-reference': '/page/terms-of-reference-for-working-groups'
    '/network-association/events': '/about-us/events'
    '/network-association/special-interest-groups/europeana-impact-community': '/page/europeana-impact-community'
    '/network-association/special-interest-groups/europeana-copyright': '/page/europeana-copyright'
    '/resources/standardization-tools/glossary': '/page/glossary'
    '/services/data-publication-services/existing-provider': '/share-your-data/process'
    '/page/edm-case-studies': '/share-your-data/metadata'
    '/page/provide-data-edm': '/share-your-data/metadata'
    '/resources/standardization-tools/edm-documentation': '/page/edm-documentation'
    '/page/mapping-to-edm-overview': '/page/edm-profiles'
    '/page/rights-statements-an-introduction': '/page/submitting-a-rights-statement'
    '/resources/standardization-tools/europeana-licensing-framework': '/page/europeana-licensing-framework'
    '/resources/standardization-tools': '/about-us/mission'
    '/resources/statistics/enumerate': '/page/enumerate'
    '/resources/standardization-tools/impact/': '/page/impact'
    '/post/europeana-media-policy': '/page/media-policy'

    # More new redirects for "Redesign 2019 / 2020", as provided by Dasha on 2020-03-13
    '/page/new-provider': '/share-your-data/process'
    '/page/existing-provider': '/share-your-data/process'
    '/our-network/network-association-members': '/network-association/members'
    '/get-involved/campaigns/allezculture': '/page/campaigns'
    '/get-involved/europeana-tech/europeanatech-insight': '/page/europeanatech-insight'
    '/get-involved/europeana-ipr/advocacy': '/page/advocacy-framework'
    '/get-involved/europeana-ipr/the-licensing-framework': '/page/europeana-licensing-framework'
    '/get-involved/europeana-ipr': '/share-your-data/copyright'
    '/share-your-data/how-to-contribute-data': '/share-your-data/process'
    '/share-your-data/data-guidelines': '/share-your-data/process'
    '/share-your-data/data-guidelines/edm-documentation': '/share-your-data/metadata'
    '/get-involved/europeana-ipr/tools-resources/presentations-and-videos': '/share-your-data/copyright'
    '/case-studies-edm': '/share-your-data/metadata'
    '/share-your-data/europeana-semantic-enrichment': '/share-your-data/enrichment'
    '/get-involved/europeana-tech/europeanatech-task-forces/hierarchical-objects': '/project/hierarchical-objects'
    '/edm-profiles': '/share-your-data/metadata'
    '/page/provider-faqs': '/share-your-data/process'
    '/web/guest/provide-data': '/share-your-data/process'
    '/resources/apis/europeana-rest-api': '/page/intro'
    '/page/educationcasestudies': '/page/education'
    '/page/europeana4education-community': '/page/europeana-education'
    '/page/educationalpartnerships': '/page/education'
    '/page/educational-resources': '/page/education'
    '/page/smoke-signals-from-the-european-parliament': '/post/copyright-advocacy-update-smoke-signals-from-the-european-parliament'
    '/page/public-domain-calculator': '/page/selecting-a-rights-statement'
    '/page/brand-values': '/about-us/mission'
    '/page/our-vision': '/about-us/mission'
    '/page/how-to-contribute-data': '/share-your-data/process'
    '/page/become-a-data-provider': '/share-your-data/process'
    '/page/network-association-newsletters': '/network-association/sign-up'

    # Additional redirects, added by Bob on 2020-05-22
    '/services/facilitating-innovation/take-the-challenge': '/about-us/services-and-tools'
    '/network-association/network-members': '/network-association/members'
    '/pro-blog/-/blogs/how-the-rijksmuseum-opened-up-its-collection-a-case-study': '/post/how-the-rijksmuseum-opened-up-its-collection-a-case-study'
    '/documents/858566/858665/Democratising+the+Rijksmuseum': '/files/Europeana_Professional/Publications/Democratising%20the%20Rijksmuseum.pdf'
    '/what-we-do/academic-research': '/page/research'
    '/page/academic-research': '/page/research'

    # Extra loops
    '/page/allezculture': '/page/campaigns'
    '/what-we-do/advocacy': '/page/advocacy-framework'
    '/resources/resources-standardisation/the-licensing-framework': '/page/europeana-licensing-framework'
    '/what-we-do/standardisation': '/share-your-data/copyright'
    '/resources/resources-standardisation/edm-documentation': '/share-your-data/metadata'

#    page:
#        from: '{slug:segment}.html'
#        to: '/page/{slug}'

# Variables
#
# A simple array to make variable replacements in destination paths using the
# {@<variable>} syntax.

variables:

# JIT (Just In Time) Replacements
#
# These replacements are made just before the actual redirect, so they
# must match any parts in `to` patterns from the above array.
#
# For conciseness, try to match an entire destination, as other URIs
# could be inadvertantly affected. If other URIs won't contain the
# string, then you can keep it as short as needed.
#
# Also, regular expressions are allowed here. Capture with \\n.
jits:
#    test:
#        replace: 'page/test2'
#        with: 'page/test'
