# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/content/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false

communities:
    name: Communities
    slug: communities
    singular_name: Community
    singular_slug: community
    behaves_like: categories
    multiple: false
    options:
        tech: EuropeanaTech
        ipr: EuropeanaIPR
        education: Europeana4Education
        research: Europeana Research
        member-states: Member States
        fashion: Europeana Fashion
        art: Europeana Art
        photo: Europeana Photography
    postfix: "Select one of the communities to activate the branding for that community in the website."

markets:
    name: Markets
    slug: markets
    singular_name: Market
    singular_slug: market
    behaves_like: categories
    multiple: true
    options:
        academic-research: Academic Research
        chis: Cultural Heritage Institutions
        creative-industries: Creative industries
        education: Education
        culture-lover: Culture lover
    postfix: "Select one or more markets"

categories:
    name: Service Categories
    slug: categories
    singular_name: Service Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options:
        advocacy: Advocacy
        api: API
        campaigns: Campaigns
        collections: Collections
        data-publication: Data publication
        data-standards: Data standards
        funding: Funding
        impact-framework: Impact framework
        legal-standards: Legal standards
        network: Network
        projects: Projects
        statistics: Statistics
#        legal_interoperability: Legal interoperability of data
#        crossdomain_exchange: Cross-domain data exchange of interoperability
#        thematic_collections: Thematic Collections
#        curated_datasets: Curated datasets
#        workshops: Workshops
#        project_brokerage: EU project brokerage and support
#        collections_publication: Collections publication
#        virtual_ehibitions: Virtual Exhibitions
#        network_association: Network Association
#        year_of_cultural_heritage: Year of Cultural Heritage
    postfix: "Select one or more categories"

##############################################
# categorization for APP contenttype
#   - appthemes
#   - appcategories
#   - apptags
#

# TODO: Convert to datatype field
appthemes:
    slug: appthemes
    name: Type
    singular_slug: type
    singular_name: Type
    behaves_like: categories
    options: [Showcase, Tools]

# TODO: Convert to itemtype category
appcategories:
    name: Theme
    slug: appcategories
    singular_name: Theme
    singular_slug: theme
    behaves_like: categories
    multiple: 1
    options: [API Implementation, Discovery, Hackathon Prototype, R&D Results, Curation/Annotation,Education, Client Library, Pilot, Gaming, Distribution, Tourism, Linked Open Data]

# TODO: convert to plain tags
apptags:
    slug: apptags
    name: Tags
    singular_name: Tag
    behaves_like: tags

##############################################
# categorization for DATA contenttype
#   - itemtype
#   - languagecoverage
#   - subjects
#   - spatialcoverage
#   - country
#   - timecoverage
#

itemtype:
    name: Item type
    slug: itemtype
    singular_name: Item type
    singular_slug: itemtype
    behaves_like: categories
    options:
        - "Audio"
        - "Books"
        - "Documents"
        - "Drawings"
        - "Film / Video"
        - "Letters & Diaries"
        - "Manuscripts"
        - "Maps"
        - "Newspapers"
        - "Paintings"
        - "Pamphlets"
        - "Periodicals"
        - "Photographs"
        - "Postcards"
        - "Posters"
        - "Prints"
        - "Sheet Music"
        - "API Implementation"
        - "Discovery"
        - "Hackathon Prototype"
        - "R&D Results"
        - "Curation / Annotation"
        - "Education"
        - "Client Library"
        - "Pilot"
        - "Gaming"
        - "Distribution"
        - "Tourism"
        - "Linked Open Data"
        # Europeana can enter more terms here, if needed.
    multiple: true
    autocomplete: true

languagecoverage:
    name: Language coverage
    slug: languagecoverage
    singular_name: Language coverage
    singular_slug: languagecoverage
    behaves_like: categories
    options:
        - "Afar"
        - "Abkhazian"
        - "Achinese"
        - "Acoli"
        - "Adangme"
        - "Adyghe; Adygei"
        - "Afro-Asiatic languages"
        - "Afrihili"
        - "Afrikaans"
        - "Ainu"
        - "Akan"
        - "Akkadian"
        - "Albanian"
        - "Aleut"
        - "Algonquian languages"
        - "Southern Altai"
        - "Amharic"
        - "English, Old (ca.450-1100)"
        - "Angika"
        - "Apache languages"
        - "Arabic"
        - "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"
        - "Aragonese"
        - "Armenian"
        - "Mapudungun; Mapuche"
        - "Arapaho"
        - "Artificial languages"
        - "Arawak"
        - "Assamese"
        - "Asturian; Bable; Leonese; Asturleonese"
        - "Athapascan languages"
        - "Australian languages"
        - "Avaric"
        - "Avestan"
        - "Awadhi"
        - "Aymara"
        - "Azerbaijani"
        - "Banda languages"
        - "Bamileke languages"
        - "Bashkir"
        - "Baluchi"
        - "Bambara"
        - "Balinese"
        - "Basque"
        - "Basa"
        - "Baltic languages"
        - "Beja; Bedawiyet"
        - "Belarusian"
        - "Bemba"
        - "Bengali"
        - "Berber languages"
        - "Bhojpuri"
        - "Bihari languages"
        - "Bikol"
        - "Bini; Edo"
        - "Bislama"
        - "Siksika"
        - "Bantu languages"
        - "Bosnian"
        - "Braj"
        - "Breton"
        - "Batak languages"
        - "Buriat"
        - "Buginese"
        - "Bulgarian"
        - "Burmese"
        - "Blin; Bilin"
        - "Caddo"
        - "Central American Indian languages"
        - "Galibi Carib"
        - "Catalan; Valencian"
        - "Caucasian languages"
        - "Cebuano"
        - "Celtic languages"
        - "Chamorro"
        - "Chibcha"
        - "Chechen"
        - "Chagatai"
        - "Chinese"
        - "Chuukese"
        - "Mari"
        - "Chinook jargon"
        - "Choctaw"
        - "Chipewyan; Dene Suline"
        - "Cherokee"
        - "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"
        - "Chuvash"
        - "Cheyenne"
        - "Chamic languages"
        - "Coptic"
        - "Cornish"
        - "Corsican"
        - "Creoles and pidgins, English based"
        - "Creoles and pidgins, French-based"
        - "Creoles and pidgins, Portuguese-based"
        - "Cree"
        - "Crimean Tatar; Crimean Turkish"
        - "Creoles and pidgins"
        - "Kashubian"
        - "Cushitic languages"
        - "Czech"
        - "Dakota"
        - "Danish"
        - "Dargwa"
        - "Land Dayak languages"
        - "Delaware"
        - "Slave (Athapascan)"
        - "Dogrib"
        - "Dinka"
        - "Divehi; Dhivehi; Maldivian"
        - "Dogri"
        - "Dravidian languages"
        - "Lower Sorbian"
        - "Duala"
        - "Dutch, Middle (ca.1050-1350)"
        - "Dutch; Flemish"
        - "Dyula"
        - "Dzongkha"
        - "Efik"
        - "Egyptian (Ancient)"
        - "Ekajuk"
        - "Elamite"
        - "English"
        - "English, Middle (1100-1500)"
        - "Esperanto"
        - "Estonian"
        - "Ewe"
        - "Ewondo"
        - "Fang"
        - "Faroese"
        - "Fanti"
        - "Fijian"
        - "Filipino; Pilipino"
        - "Finnish"
        - "Finno-Ugrian languages"
        - "Fon"
        - "French"
        - "French, Middle (ca.1400-1600)"
        - "French, Old (842-ca.1400)"
        - "Northern Frisian"
        - "Eastern Frisian"
        - "Western Frisian"
        - "Fulah"
        - "Friulian"
        - "Ga"
        - "Gayo"
        - "Gbaya"
        - "Germanic languages"
        - "Georgian"
        - "German"
        - "Geez"
        - "Gilbertese"
        - "Gaelic; Scottish Gaelic"
        - "Irish"
        - "Galician"
        - "Manx"
        - "German, Middle High (ca.1050-1500)"
        - "German, Old High (ca.750-1050)"
        - "Gondi"
        - "Gorontalo"
        - "Gothic"
        - "Grebo"
        - "Greek, Ancient (to 1453)"
        - "Greek, Modern (1453-)"
        - "Guarani"
        - "Swiss German; Alemannic; Alsatian"
        - "Gujarati"
        - "Gwich'in"
        - "Haida"
        - "Haitian; Haitian Creole"
        - "Hausa"
        - "Hawaiian"
        - "Hebrew"
        - "Herero"
        - "Hiligaynon"
        - "Himachali languages; Western Pahari languages"
        - "Hindi"
        - "Hittite"
        - "Hmong; Mong"
        - "Hiri Motu"
        - "Croatian"
        - "Upper Sorbian"
        - "Hungarian"
        - "Hupa"
        - "Iban"
        - "Igbo"
        - "Icelandic"
        - "Ido"
        - "Sichuan Yi; Nuosu"
        - "Ijo languages"
        - "Inuktitut"
        - "Interlingue; Occidental"
        - "Iloko"
        - "Interlingua (International Auxiliary Language Association)"
        - "Indic languages"
        - "Indonesian"
        - "Indo-European languages"
        - "Ingush"
        - "Inupiaq"
        - "Iranian languages"
        - "Iroquoian languages"
        - "Italian"
        - "Javanese"
        - "Lojban"
        - "Japanese"
        - "Judeo-Persian"
        - "Judeo-Arabic"
        - "Kara-Kalpak"
        - "Kabyle"
        - "Kachin; Jingpho"
        - "Kalaallisut; Greenlandic"
        - "Kamba"
        - "Kannada"
        - "Karen languages"
        - "Kashmiri"
        - "Kanuri"
        - "Kawi"
        - "Kazakh"
        - "Kabardian"
        - "Khasi"
        - "Khoisan languages"
        - "Central Khmer"
        - "Khotanese; Sakan"
        - "Kikuyu; Gikuyu"
        - "Kinyarwanda"
        - "Kirghiz; Kyrgyz"
        - "Kimbundu"
        - "Konkani"
        - "Komi"
        - "Kongo"
        - "Korean"
        - "Kosraean"
        - "Kpelle"
        - "Karachay-Balkar"
        - "Karelian"
        - "Kru languages"
        - "Kurukh"
        - "Kuanyama; Kwanyama"
        - "Kumyk"
        - "Kurdish"
        - "Kutenai"
        - "Ladino"
        - "Lahnda"
        - "Lamba"
        - "Lao"
        - "Latin"
        - "Latvian"
        - "Lezghian"
        - "Limburgan; Limburger; Limburgish"
        - "Lingala"
        - "Lithuanian"
        - "Mongo"
        - "Lozi"
        - "Luxembourgish; Letzeburgesch"
        - "Luba-Lulua"
        - "Luba-Katanga"
        - "Ganda"
        - "Luiseno"
        - "Lunda"
        - "Luo (Kenya and Tanzania)"
        - "Lushai"
        - "Macedonian"
        - "Madurese"
        - "Magahi"
        - "Marshallese"
        - "Maithili"
        - "Makasar"
        - "Malayalam"
        - "Mandingo"
        - "Maori"
        - "Austronesian languages"
        - "Marathi"
        - "Masai"
        - "Malay"
        - "Moksha"
        - "Mandar"
        - "Mende"
        - "Irish, Middle (900-1200)"
        - "Mi'kmaq; Micmac"
        - "Minangkabau"
        - "Uncoded languages"
        - "Mon-Khmer languages"
        - "Malagasy"
        - "Maltese"
        - "Manchu"
        - "Manipuri"
        - "Manobo languages"
        - "Mohawk"
        - "Mongolian"
        - "Mossi"
        - "Multiple languages"
        - "Munda languages"
        - "Creek"
        - "Mirandese"
        - "Marwari"
        - "Mayan languages"
        - "Erzya"
        - "Nahuatl languages"
        - "North American Indian languages"
        - "Neapolitan"
        - "Nauru"
        - "Navajo; Navaho"
        - "Ndebele, South; South Ndebele"
        - "Ndebele, North; North Ndebele"
        - "Ndonga"
        - "Low German; Low Saxon; German, Low; Saxon, Low"
        - "Nepali"
        - "Nepal Bhasa; Newari"
        - "Nias"
        - "Niger-Kordofanian languages"
        - "Niuean"
        - "Norwegian Nynorsk; Nynorsk, Norwegian"
        - "BokmÂl, Norwegian; Norwegian BokmÂl"
        - "Nogai"
        - "Norse, Old"
        - "Norwegian"
        - "N'Ko"
        - "Pedi; Sepedi; Northern Sotho"
        - "Nubian languages"
        - "Classical Newari; Old Newari; Classical Nepal Bhasa"
        - "Chichewa; Chewa; Nyanja"
        - "Nyamwezi"
        - "Nyankole"
        - "Nyoro"
        - "Nzima"
        - "Occitan (post 1500)"
        - "Ojibwa"
        - "Oriya"
        - "Oromo"
        - "Osage"
        - "Ossetian; Ossetic"
        - "Turkish, Ottoman (1500-1928)"
        - "Otomian languages"
        - "Papuan languages"
        - "Pangasinan"
        - "Pahlavi"
        - "Pampanga; Kapampangan"
        - "Panjabi; Punjabi"
        - "Papiamento"
        - "Palauan"
        - "Persian, Old (ca.600-400 B.C.)"
        - "Persian"
        - "Philippine languages"
        - "Phoenician"
        - "Pali"
        - "Polish"
        - "Pohnpeian"
        - "Portuguese"
        - "Prakrit languages"
        - "ProvenÁal, Old (to 1500); Occitan, Old (to 1500)"
        - "Pushto; Pashto"
        - "Reserved for local use"
        - "Quechua"
        - "Rajasthani"
        - "Rapanui"
        - "Rarotongan; Cook Islands Maori"
        - "Romance languages"
        - "Romansh"
        - "Romany"
        - "Romanian"
        - "Rundi"
        - "Aromanian; Arumanian; Macedo-Romanian"
        - "Russian"
        - "Sandawe"
        - "Sango"
        - "Yakut"
        - "South American Indian languages"
        - "Salishan languages"
        - "Samaritan Aramaic"
        - "Sanskrit"
        - "Sasak"
        - "Santali"
        - "Sicilian"
        - "Scots"
        - "Selkup"
        - "Semitic languages"
        - "Irish, Old (to 900)"
        - "Sign Languages"
        - "Shan"
        - "Sidamo"
        - "Sinhala; Sinhalese"
        - "Siouan languages"
        - "Sino-Tibetan languages"
        - "Slavic languages"
        - "Slovak"
        - "Slovenian"
        - "Southern Sami"
        - "Northern Sami"
        - "Sami languages"
        - "Lule Sami"
        - "Inari Sami"
        - "Samoan"
        - "Skolt Sami"
        - "Shona"
        - "Sindhi"
        - "Soninke"
        - "Sogdian"
        - "Somali"
        - "Songhai languages"
        - "Sotho, Southern"
        - "Spanish; Castilian"
        - "Sardinian"
        - "Sranan Tongo"
        - "Serbian"
        - "Serer"
        - "Nilo-Saharan languages"
        - "Swati"
        - "Sukuma"
        - "Sundanese"
        - "Susu"
        - "Sumerian"
        - "Swahili"
        - "Swedish"
        - "Classical Syriac"
        - "Syriac"
        - "Tahitian"
        - "Tai languages"
        - "Tamil"
        - "Tatar"
        - "Telugu"
        - "Timne"
        - "Tereno"
        - "Tetum"
        - "Tajik"
        - "Tagalog"
        - "Thai"
        - "Tibetan"
        - "Tigre"
        - "Tigrinya"
        - "Tiv"
        - "Tokelau"
        - "Klingon; tlhIngan-Hol"
        - "Tlingit"
        - "Tamashek"
        - "Tonga (Nyasa)"
        - "Tonga (Tonga Islands)"
        - "Tok Pisin"
        - "Tsimshian"
        - "Tswana"
        - "Tsonga"
        - "Turkmen"
        - "Tumbuka"
        - "Tupi languages"
        - "Turkish"
        - "Altaic languages"
        - "Tuvalu"
        - "Twi"
        - "Tuvinian"
        - "Udmurt"
        - "Ugaritic"
        - "Uighur; Uyghur"
        - "Ukrainian"
        - "Umbundu"
        - "Undetermined"
        - "Urdu"
        - "Uzbek"
        - "Vai"
        - "Venda"
        - "Vietnamese"
        - "Volap¸k"
        - "Votic"
        - "Wakashan languages"
        - "Wolaitta; Wolaytta"
        - "Waray"
        - "Washo"
        - "Welsh"
        - "Sorbian languages"
        - "Walloon"
        - "Wolof"
        - "Kalmyk; Oirat"
        - "Xhosa"
        - "Yao"
        - "Yapese"
        - "Yiddish"
        - "Yoruba"
        - "Yupik languages"
        - "Zapotec"
        - "Blissymbols; Blissymbolics; Bliss"
        - "Zenaga"
        - "Standard Moroccan Tamazight"
        - "Zhuang; Chuang"
        - "Zande languages"
        - "Zulu"
        - "Zuni"
    multiple: true
    autocomplete: true

subjects:
    name: Subjects
    slug: subjects
    singular_name: Subject
    singular_slug: subject
    behaves_like: categories
    options:
        - "Ancient History"
        - "Cartography"
        - "Geography"
        - "Literature"
        - "Medieval History"
        - "Military History"
        - "Religious"
        - "Religious Literature"
        - "Theology"
        - "World War 1914-1918"
        - "World War 1940-1945"
        - "Philosophy"
        # Europeana can enter more terms here, if needed.
    multiple: true
    autocomplete: true


spatialcoverage:
    name: Spatial coverage
    slug: spatialcoverage
    singular_name: Spatial coverage
    singular_slug: spatialcoverage
    behaves_like: categories
    options:
        - "Northern Europe"
        - "Western Europe"
        - "Southern Europe"
        - "Eastern Europe"
        - "Middle East"
        - "Asia"
        - "North America"
        - "Latin America"
        - "Oceania"
        - "Africa"
        - "Multiple Areas"
        # Europeana can enter more terms here, if needed.
    multiple: true
    autocomplete: true

country:
    name: Country
    slug: country
    singular_name: Country
    singular_slug: country
    behaves_like: categories
    options:
        - "Albania"
        - "Andorra"
        - "Austria"
        - "Belarus"
        - "Belgium"
        - "Bosnia And Herzegovina"
        - "Bulgaria"
        - "Canary Islands"
        - "Croatia"
        - "Czech Republic"
        - "Denmark"
        - "Estonia"
        - "European Union"
        - "Faroe Islands"
        - "Finland"
        - "France"
        - "Georgia"
        - "Germany"
        - "Greece"
        - "Guernsey"
        - "Hungary"
        - "Iceland"
        - "Ireland"
        - "Isle Of Man"
        - "Italy"
        - "Jersey"
        - "Latvia"
        - "Liechtenstein"
        - "Lithuania"
        - "Luxembourg"
        - "Malta"
        - "Moldova"
        - "Monaco"
        - "Montenegro"
        - "Netherlands"
        - "Norway"
        - "Poland"
        - "Portugal"
        - "Republic of Macedonia"
        - "Romania"
        - "San Marino"
        - "Serbia"
        - "Serbien und Montenegro"
        - "Slovakia"
        - "Slovenia"
        - "Soviet Union"
        - "Spain"
        - "Svalbard And Jan Mayen"
        - "Sweden"
        - "Switzerland"
        - "Ukraine"
        - "United Kingdom"
        - "Vatican City"
    multiple: true
    autocomplete: true

timecoverage:
    name: Time coverage
    slug: timecoverage
    singular_name: Time coverage
    singular_slug: timecoverage
    behaves_like: categories
    options:
        - "Ancient World"
        - "Medieval"
        - "Early Modern"
        - "18th Century"
        - "19th Century"
        - "1900-1945"
        - "1945 Onwards"
        - "Multiple Eras"
    multiple: true
    autocomplete: true
